name: Deploy Preview

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  deploy-docs:
    permissions:
      contents: write #  to write to gh-pages branch (peaceiris/actions-gh-pages)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install packages
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm run build:website

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@329bcc8f12caed2cefe5a5b80781499a6f3b361b # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist
          cname: cli-testing.com
