name: Deploy Preview

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  deploy-docs:
    permissions:
      contents: write #  to write to gh-pages branch (peaceiris/actions-gh-pages)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install packages
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm run build:website

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist
          cname: cli-testing.com
